export const REQUESTED = "REQUESTED";
export const REQUESTED_FAILED = "REQUESTED_FAILED";

export const REQUESTED_ARTICLES_SUCCEEDED = "REQUESTED_ARTICLES_SUCCEEDED";
export const FETCHED_ARTICLES = "FETCHED_ARTICLES";

export const REQUESTED_ARTICLE_SUCCEEDED = "REQUESTED_ARTICLE_SUCCEEDED";
export const FETCHED_ARTICLE = "FETCHED_ARTICLE";

export const REQUESTED_USER_SUCCEEDED = "REQUESTED_USER_SUCCEEDED";

export const REQUESTED_ARTICLE_COMMENTS_SUCCEEDED =
  "REQUESTED_ARTICLE_COMMENTS_SUCCEEDED";

export const FETCHED_ARTICLES_SEARCH = "FETCHED_ARTICLES_SEARCH";
export const RESET_ARTICLES_SEARCH = "RESET_ARTICLES_SEARCH";
export const SET_SEARCH = "SET_SEARCH";
export const REQUESTED_ARTICLES_SEARCH_SUCCEEDED =
  "REQUESTED_ARTICLES_SEARCH_SUCCEEDED";
